openapi: 3.0.0
info:
  title: Job Crawler API
  description: 사람인 데이터를 기반으로 한 구인구직 백엔드 API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: 로컬 개발 서버
paths:
  /jobs:
    get:
      summary: 모든 채용 공고 조회
      description: 채용 공고 목록을 페이지네이션, 필터링, 정렬하여 조회합니다.
      parameters:
        - name: page
          in: query
          description: 현재 페이지 번호 (기본값: 1)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: 페이지당 항목 수 (기본값: 20)
          required: false
          schema:
            type: integer
        - name: company
          in: query
          description: 필터링할 회사명
          required: false
          schema:
            type: string
        - name: location
          in: query
          description: 필터링할 지역
          required: false
          schema:
            type: string
        - name: experience
          in: query
          description: 필터링할 경력
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: 필터링할 채용 제목
          required: false
          schema:
            type: string
        - name: sort_by
          in: query
          description: 정렬 기준 필드 (기본값: 마감일)
          required: false
          schema:
            type: string
        - name: sort_order
          in: query
          description: 정렬 순서 (asc 또는 desc, 기본값: asc)
          required: false
          schema:
            type: string
      responses:
        200:
          description: 성공적으로 데이터를 반환합니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        회사명:
                          type: string
                        제목:
                          type: string
                        링크:
                          type: string
                        지역:
                          type: string
                        경력:
                          type: string
                        학력:
                          type: string
                        고용형태:
                          type: string
                        마감일:
                          type: string
                        직무분야:
                          type: string
                        연봉정보:
                          type: string
                  pagination:
                    type: object
                    properties:
                      currentPage:
                        type: integer
                      limit:
                        type: integer
                      totalItems:
                        type: integer
                      totalPages:
                        type: integer
  /jobs/all:
    get:
      summary: 모든 채용 공고 조회 (페이지네이션 없음)
      description: 필터링 조건에 맞는 모든 채용 공고를 반환합니다.
      parameters:
        - name: company
          in: query
          description: 필터링할 회사명
          required: false
          schema:
            type: string
        - name: location
          in: query
          description: 필터링할 지역
          required: false
          schema:
            type: string
        - name: experience
          in: query
          description: 필터링할 경력
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: 필터링할 채용 제목
          required: false
          schema:
            type: string
      responses:
        200:
          description: 성공적으로 데이터를 반환합니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        회사명:
                          type: string
                        제목:
                          type: string
                        링크:
                          type: string
                        지역:
                          type: string
                        경력:
                          type: string
                        학력:
                          type: string
                        고용형태:
                          type: string
                        마감일:
                          type: string
                        직무분야:
                          type: string
                        연봉정보:
                          type: string
                  totalItems:
                    type: integer
